In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import openpmd_api as io

In [2]:
series = io.Series('diags/openPMD/monitor.bp5', io.Access.read_only)

In [3]:
iters = list(series.iterations)
print(len(iters), 'iterations in file')

5 iterations in file

In [5]:
beam0 = series.iterations[iters[0]].particles["beam"]

In [6]:
df0 = beam0.to_df()
print(df0.columns)

Index(['id', 'momentum_t', 'momentum_x', 'momentum_y', 'position_t',
       'position_x', 'position_y', 'positionOffset_t', 'positionOffset_x',
       'positionOffset_y', 'qm', 'spin_x', 'spin_y', 'spin_z', 'weighting'],
      dtype='str')

In [7]:
testparticles0 = df0[df0['weighting'] == 0.0]

In [8]:
len(testparticles0)

50

In [9]:
testparticles0.iloc[0]

id                  9.223374e+18
momentum_t          0.000000e+00
momentum_x          0.000000e+00
momentum_y          0.000000e+00
position_t          0.000000e+00
position_x          1.000000e-08
position_y          0.000000e+00
positionOffset_t    0.000000e+00
positionOffset_x    0.000000e+00
positionOffset_y    0.000000e+00
qm                  1.065789e+03
spin_x              0.000000e+00
spin_y              0.000000e+00
spin_z              0.000000e+00
weighting           0.000000e+00
Name: 21846, dtype: float64

In [10]:
testparticles0['position_x']

row
21846     1.000000e-08
21847     1.863506e-03
21848     3.727013e-03
21849     5.590519e-03
21850     7.454025e-03
21851     0.000000e+00
21852     0.000000e+00
21853     0.000000e+00
21854     0.000000e+00
21855     0.000000e+00
43702     9.317532e-03
43703     1.118104e-02
43704     1.304454e-02
43705     1.490805e-02
43706     0.000000e+00
43707     0.000000e+00
43708     0.000000e+00
43709     0.000000e+00
65555     1.677156e-02
65556     1.863506e-02
65557     2.049857e-02
65558     2.236208e-02
65559     0.000000e+00
65560     0.000000e+00
65561     0.000000e+00
65562     0.000000e+00
87408     2.422558e-02
87409     2.608909e-02
87410     2.795259e-02
87411     2.981610e-02
87412     0.000000e+00
87413     0.000000e+00
87414     0.000000e+00
87415     0.000000e+00
109261    3.167961e-02
109262    3.354311e-02
109263    3.540662e-02
109264    3.727013e-02
109265    0.000000e+00
109266    0.000000e+00
109267    0.000000e+00
109268    0.000000e+00
131114    3.913363e-02
131115    4.099714e-02
131116    4.286065e-02
131117    4.472415e-02
131118    0.000000e+00
131119    0.000000e+00
131120    0.000000e+00
131121    0.000000e+00
Name: position_x, dtype: float64

In [32]:
testparticles0[['position_x', 'position_y', 'id']]

          position_x    position_y                   id
row
21846   1.000000e-08  0.000000e+00  9223374235894808576
21847   1.863506e-03  0.000000e+00  9223374235911585792
21848   3.727013e-03  0.000000e+00  9223374235928363008
21849   5.590519e-03  0.000000e+00  9223374235945140224
21850   7.454025e-03  0.000000e+00  9223374235961917440
21851   0.000000e+00  1.000000e-08  9223374236314238976
21852   0.000000e+00  6.035083e-04  9223374236331016192
21853   0.000000e+00  1.207017e-03  9223374236347793408
21854   0.000000e+00  1.810525e-03  9223374236364570624
21855   0.000000e+00  2.414033e-03  9223374236381347840
43702   9.317532e-03  0.000000e+00  9223374235978694656
43703   1.118104e-02  0.000000e+00  9223374235995471872
43704   1.304454e-02  0.000000e+00  9223374236012249088
43705   1.490805e-02  0.000000e+00  9223374236029026304
43706   0.000000e+00  3.017541e-03  9223374236398125056
43707   0.000000e+00  3.621050e-03  9223374236414902272
43708   0.000000e+00  4.224558e-03  9223374236431679488
43709   0.000000e+00  4.828066e-03  9223374236448456704
65555   1.677156e-02  0.000000e+00  9223374236045803520
65556   1.863506e-02  0.000000e+00  9223374236062580736
65557   2.049857e-02  0.000000e+00  9223374236079357952
65558   2.236208e-02  0.000000e+00  9223374236096135168
65559   0.000000e+00  5.431574e-03  9223374236465233920
65560   0.000000e+00  6.035083e-03  9223374236482011136
65561   0.000000e+00  6.638591e-03  9223374236498788352
65562   0.000000e+00  7.242099e-03  9223374236515565568
87408   2.422558e-02  0.000000e+00  9223374236112912384
87409   2.608909e-02  0.000000e+00  9223374236129689600
87410   2.795259e-02  0.000000e+00  9223374236146466816
87411   2.981610e-02  0.000000e+00  9223374236163244032
87412   0.000000e+00  7.845607e-03  9223374236532342784
87413   0.000000e+00  8.449116e-03  9223374236549120000
87414   0.000000e+00  9.052624e-03  9223374236565897216
87415   0.000000e+00  9.656132e-03  9223374236582674432
109261  3.167961e-02  0.000000e+00  9223374236180021248
109262  3.354311e-02  0.000000e+00  9223374236196798464
109263  3.540662e-02  0.000000e+00  9223374236213575680
109264  3.727013e-02  0.000000e+00  9223374236230352896
109265  0.000000e+00  1.025964e-02  9223374236599451648
109266  0.000000e+00  1.086315e-02  9223374236616228864
109267  0.000000e+00  1.146666e-02  9223374236633006080
109268  0.000000e+00  1.207017e-02  9223374236649783296
131114  3.913363e-02  0.000000e+00  9223374236247130112
131115  4.099714e-02  0.000000e+00  9223374236263907328
131116  4.286065e-02  0.000000e+00  9223374236280684544
131117  4.472415e-02  0.000000e+00  9223374236297461760
131118  0.000000e+00  1.267367e-02  9223374236666560512
131119  0.000000e+00  1.327718e-02  9223374236683337728
131120  0.000000e+00  1.388069e-02  9223374236700114944
131121  0.000000e+00  1.448420e-02  9223374236716892160

In [12]:
dir(testparticles0)

['T',
 '_AXIS_LEN',
 '_AXIS_ORDERS',
 '_AXIS_TO_AXIS_NUMBER',
 '_HANDLED_TYPES',
 '__abs__',
 '__add__',
 '__and__',
 '__annotations__',
 '__array__',
 '__array_priority__',
 '__array_ufunc__',
 '__arrow_c_stream__',
 '__bool__',
 '__class__',
 '__contains__',
 '__copy__',
 '__dataframe__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__firstlineno__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pandas_priority__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rmatmul__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__setitem__',
 '__setstate__',
 '__sizeof__',
 '__static_attributes__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__weakref__',
 '__xor__',
 '_accessors',
 '_accum_func',
 '_agg_examples_doc',
 '_agg_see_also_doc',
 '_align_for_op',
 '_align_frame',
 '_align_series',
 '_append_internal',
 '_arith_method',
 '_arith_method_with_reindex',
 '_attrs',
 '_box_col_values',
 '_can_fast_transpose',
 '_check_copy_deprecation',
 '_check_inplace_and_allows_duplicate_labels',
 '_check_label_or_level_ambiguity',
 '_clip_with_one_bound',
 '_clip_with_scalar',
 '_cmp_method',
 '_combine_frame',
 '_consolidate',
 '_consolidate_inplace',
 '_construct_axes_dict',
 '_construct_result',
 '_constructor',
 '_constructor_from_mgr',
 '_constructor_sliced',
 '_constructor_sliced_from_mgr',
 '_dir_additions',
 '_dir_deletions',
 '_dispatch_frame_op',
 '_drop_axis',
 '_drop_labels_or_levels',
 '_ensure_valid_index',
 '_find_valid_index',
 '_flags',
 '_flex_arith_method',
 '_flex_cmp_method',
 '_from_arrays',
 '_from_mgr',
 '_get_agg_axis',
 '_get_axis',
 '_get_axis_name',
 '_get_axis_number',
 '_get_axis_resolvers',
 '_get_block_manager_axis',
 '_get_bool_data',
 '_get_cleaned_column_resolvers',
 '_get_column_array',
 '_get_index_resolvers',
 '_get_item',
 '_get_label_or_level_values',
 '_get_numeric_data',
 '_get_value',
 '_get_values_for_csv',
 '_getitem_bool_array',
 '_getitem_multilevel',
 '_getitem_slice',
 '_gotitem',
 '_hidden_attrs',
 '_indexed_same',
 '_info_axis',
 '_info_axis_name',
 '_info_axis_number',
 '_info_repr',
 '_init_mgr',
 '_inplace_method',
 '_internal_names',
 '_internal_names_set',
 '_is_homogeneous_type',
 '_is_label_or_level_reference',
 '_is_label_reference',
 '_is_level_reference',
 '_is_mixed_type',
 '_iset_item',
 '_iset_item_mgr',
 '_iset_not_inplace',
 '_iter_column_arrays',
 '_ixs',
 '_logical_func',
 '_logical_method',
 '_maybe_align_series_as_frame',
 '_metadata',
 '_mgr',
 '_min_count_stat_function',
 '_module_source',
 '_needs_reindex_multi',
 '_pad_or_backfill',
 '_reduce',
 '_reduce_axis1',
 '_reindex_axes',
 '_reindex_multi',
 '_reindex_with_indexers',
 '_rename',
 '_replace_columnwise',
 '_repr_data_resource_',
 '_repr_fits_horizontal_',
 '_repr_fits_vertical_',
 '_repr_html_',
 '_repr_latex_',
 '_reset_cache',
 '_sanitize_column',
 '_select_dtypes_indices',
 '_series',
 '_set_axis',
 '_set_axis_name',
 '_set_axis_nocheck',
 '_set_item',
 '_set_item_frame_value',
 '_set_item_mgr',
 '_set_value',
 '_setitem_array',
 '_setitem_frame',
 '_setitem_slice',
 '_shift_with_freq',
 '_should_reindex_frame_op',
 '_slice',
 '_stat_function',
 '_stat_function_ddof',
 '_to_dict_of_blocks',
 '_to_latex_via_styler',
 '_typ',
 '_update_inplace',
 '_validate_dtype',
 '_values',
 '_where',
 'abs',
 'add',
 'add_prefix',
 'add_suffix',
 'agg',
 'aggregate',
 'align',
 'all',
 'any',
 'apply',
 'asfreq',
 'asof',
 'assign',
 'astype',
 'at',
 'at_time',
 'attrs',
 'axes',
 'between_time',
 'bfill',
 'boxplot',
 'clip',
 'columns',
 'combine',
 'combine_first',
 'compare',
 'convert_dtypes',
 'copy',
 'corr',
 'corrwith',
 'count',
 'cov',
 'cummax',
 'cummin',
 'cumprod',
 'cumsum',
 'describe',
 'diff',
 'div',
 'divide',
 'dot',
 'drop',
 'drop_duplicates',
 'droplevel',
 'dropna',
 'dtypes',
 'duplicated',
 'empty',
 'eq',
 'equals',
 'eval',
 'ewm',
 'expanding',
 'explode',
 'ffill',
 'fillna',
 'filter',
 'first_valid_index',
 'flags',
 'floordiv',
 'from_arrow',
 'from_dict',
 'from_records',
 'ge',
 'get',
 'groupby',
 'gt',
 'head',
 'hist',
 'iat',
 'id',
 'idxmax',
 'idxmin',
 'iloc',
 'index',
 'infer_objects',
 'info',
 'insert',
 'interpolate',
 'isetitem',
 'isin',
 'isna',
 'isnull',
 'items',
 'iterrows',
 'itertuples',
 'join',
 'keys',
 'kurt',
 'kurtosis',
 'last_valid_index',
 'le',
 'loc',
 'lt',
 'map',
 'mask',
 'max',
 'mean',
 'median',
 'melt',
 'memory_usage',
 'merge',
 'min',
 'mod',
 'mode',
 'momentum_t',
 'momentum_x',
 'momentum_y',
 'mul',
 'multiply',
 'ndim',
 'ne',
 'nlargest',
 'notna',
 'notnull',
 'nsmallest',
 'nunique',
 'pct_change',
 'pipe',
 'pivot',
 'pivot_table',
 'plot',
 'pop',
 'positionOffset_t',
 'positionOffset_x',
 'positionOffset_y',
 'position_t',
 'position_x',
 'position_y',
 'pow',
 'prod',
 'product',
 'qm',
 'quantile',
 'query',
 'radd',
 'rank',
 'rdiv',
 'reindex',
 'reindex_like',
 'rename',
 'rename_axis',
 'reorder_levels',
 'replace',
 'resample',
 'reset_index',
 'rfloordiv',
 'rmod',
 'rmul',
 'rolling',
 'round',
 'rpow',
 'rsub',
 'rtruediv',
 'sample',
 'select_dtypes',
 'sem',
 'set_axis',
 'set_flags',
 'set_index',
 'shape',
 'shift',
 'size',
 'skew',
 'sort_index',
 'sort_values',
 'spin_x',
 'spin_y',
 'spin_z',
 'squeeze',
 'stack',
 'std',
 'style',
 'sub',
 'subtract',
 'sum',
 'swaplevel',
 'tail',
 'take',
 'to_clipboard',
 'to_csv',
 'to_dict',
 'to_excel',
 'to_feather',
 'to_hdf',
 'to_html',
 'to_iceberg',
 'to_json',
 'to_latex',
 'to_markdown',
 'to_numpy',
 'to_orc',
 'to_parquet',
 'to_period',
 'to_pickle',
 'to_records',
 'to_sql',
 'to_stata',
 'to_string',
 'to_timestamp',
 'to_xarray',
 'to_xml',
 'transform',
 'transpose',
 'truediv',
 'truncate',
 'tz_convert',
 'tz_localize',
 'unstack',
 'update',
 'value_counts',
 'values',
 'var',
 'weighting',
 'where',
 'xs']

In [14]:
print(testparticles0.groupby('id', sort=False)[['position_x', 'position_y']])

<pandas.api.typing.DataFrameGroupBy object at 0x7b48d1907230>

In [15]:
type(testparticles0)

pandas.DataFrame

In [16]:
testparticles0.columns

Index(['id', 'momentum_t', 'momentum_x', 'momentum_y', 'position_t',
       'position_x', 'position_y', 'positionOffset_t', 'positionOffset_x',
       'positionOffset_y', 'qm', 'spin_x', 'spin_y', 'spin_z', 'weighting'],
      dtype='str')

In [17]:
testparticles0.groupby('id')

In [18]:
print(testparticles0.groupby('id'))

<pandas.api.typing.DataFrameGroupBy object at 0x7b48cd3695b0>

In [19]:
testparticles0.groupby('id')[['position_x', 'position_y']]

In [20]:
print(testparticles0.groupby('id')[['position_x', 'position_y']])

<pandas.api.typing.DataFrameGroupBy object at 0x7b48cd36c150>

In [23]:
for row in testparticles0.groupby('id')[['position_x', 'position_y']].itertuples():
    print(row)

AttributeError: 'DataFrameGroupBy' object has no attribute 'itertuples'

In [24]:
testparticles0.groupby('id')

50

In [28]:
testparticles0.groupby('id').columns()

AttributeError: 'DataFrameGroupBy' object has no attribute 'columns'

In [31]:
testparticles0.columns

Index(['id', 'momentum_t', 'momentum_x', 'momentum_y', 'position_t',
       'position_x', 'position_y', 'positionOffset_t', 'positionOffset_x',
       'positionOffset_y', 'qm', 'spin_x', 'spin_y', 'spin_z', 'weighting'],
      dtype='str')

In [41]:
testparticles0['id'][21846]

np.uint64(9223374235894808576)

In [43]:
idarr = testparticles0['id'].to_numpy()

In [44]:
idarr[1]-idarr[0]

np.uint64(16777216)

In [45]:
idarr[2]-idarr[1]

np.uint64(16777216)

In [46]:
idarr[1:] - idarr[0:-1]

array([            16777216,             16777216,             16777216,
                   16777216,            352321536,             16777216,
                   16777216,             16777216,             16777216,
       18446744073306898432,             16777216,             16777216,
                   16777216,            369098752,             16777216,
                   16777216,             16777216, 18446744073306898432,
                   16777216,             16777216,             16777216,
                  369098752,             16777216,             16777216,
                   16777216, 18446744073306898432,             16777216,
                   16777216,             16777216,            369098752,
                   16777216,             16777216,             16777216,
       18446744073306898432,             16777216,             16777216,
                   16777216,            369098752,             16777216,
                   16777216,             16777216, 18446744073306898432,
                   16777216,             16777216,             16777216,
                  369098752,             16777216,             16777216,
                   16777216], dtype=uint64)

In [48]:
testparticles0.iloc[0]

id                  9.223374e+18
momentum_t          0.000000e+00
momentum_x          0.000000e+00
momentum_y          0.000000e+00
position_t          0.000000e+00
position_x          1.000000e-08
position_y          0.000000e+00
positionOffset_t    0.000000e+00
positionOffset_x    0.000000e+00
positionOffset_y    0.000000e+00
qm                  1.065789e+03
spin_x              0.000000e+00
spin_y              0.000000e+00
spin_z              0.000000e+00
weighting           0.000000e+00
Name: 21846, dtype: float64

In [61]:
type(testparticles0.iloc[0]['id'])

numpy.float64

In [51]:
testparticles0['momentum_t']

row
21846     0.0
21847     0.0
21848     0.0
21849     0.0
21850     0.0
21851     0.0
21852     0.0
21853     0.0
21854     0.0
21855     0.0
43702     0.0
43703     0.0
43704     0.0
43705     0.0
43706     0.0
43707     0.0
43708     0.0
43709     0.0
65555     0.0
65556     0.0
65557     0.0
65558     0.0
65559     0.0
65560     0.0
65561     0.0
65562     0.0
87408     0.0
87409     0.0
87410     0.0
87411     0.0
87412     0.0
87413     0.0
87414     0.0
87415     0.0
109261    0.0
109262    0.0
109263    0.0
109264    0.0
109265    0.0
109266    0.0
109267    0.0
109268    0.0
131114    0.0
131115    0.0
131116    0.0
131117    0.0
131118    0.0
131119    0.0
131120    0.0
131121    0.0
Name: momentum_t, dtype: float64

In [58]:
testparticles0.loc[131121, 'position_x']

np.float64(0.0)

In [55]:
testparticles0.columns

Index(['id', 'momentum_t', 'momentum_x', 'momentum_y', 'position_t',
       'position_x', 'position_y', 'positionOffset_t', 'positionOffset_x',
       'positionOffset_y', 'qm', 'spin_x', 'spin_y', 'spin_z', 'weighting'],
      dtype='str')

In [60]:
testparticles0.loc[:,'id']

row
21846     9223374235894808576
21847     9223374235911585792
21848     9223374235928363008
21849     9223374235945140224
21850     9223374235961917440
21851     9223374236314238976
21852     9223374236331016192
21853     9223374236347793408
21854     9223374236364570624
21855     9223374236381347840
43702     9223374235978694656
43703     9223374235995471872
43704     9223374236012249088
43705     9223374236029026304
43706     9223374236398125056
43707     9223374236414902272
43708     9223374236431679488
43709     9223374236448456704
65555     9223374236045803520
65556     9223374236062580736
65557     9223374236079357952
65558     9223374236096135168
65559     9223374236465233920
65560     9223374236482011136
65561     9223374236498788352
65562     9223374236515565568
87408     9223374236112912384
87409     9223374236129689600
87410     9223374236146466816
87411     9223374236163244032
87412     9223374236532342784
87413     9223374236549120000
87414     9223374236565897216
87415     9223374236582674432
109261    9223374236180021248
109262    9223374236196798464
109263    9223374236213575680
109264    9223374236230352896
109265    9223374236599451648
109266    9223374236616228864
109267    9223374236633006080
109268    9223374236649783296
131114    9223374236247130112
131115    9223374236263907328
131116    9223374236280684544
131117    9223374236297461760
131118    9223374236666560512
131119    9223374236683337728
131120    9223374236700114944
131121    9223374236716892160
Name: id, dtype: uint64

In [63]:
type(testparticles0.loc[131121, 'id'])

numpy.uint64

In [66]:
testparticles0.loc[:, 'position_x']

row
21846     1.000000e-08
21847     1.863506e-03
21848     3.727013e-03
21849     5.590519e-03
21850     7.454025e-03
21851     0.000000e+00
21852     0.000000e+00
21853     0.000000e+00
21854     0.000000e+00
21855     0.000000e+00
43702     9.317532e-03
43703     1.118104e-02
43704     1.304454e-02
43705     1.490805e-02
43706     0.000000e+00
43707     0.000000e+00
43708     0.000000e+00
43709     0.000000e+00
65555     1.677156e-02
65556     1.863506e-02
65557     2.049857e-02
65558     2.236208e-02
65559     0.000000e+00
65560     0.000000e+00
65561     0.000000e+00
65562     0.000000e+00
87408     2.422558e-02
87409     2.608909e-02
87410     2.795259e-02
87411     2.981610e-02
87412     0.000000e+00
87413     0.000000e+00
87414     0.000000e+00
87415     0.000000e+00
109261    3.167961e-02
109262    3.354311e-02
109263    3.540662e-02
109264    3.727013e-02
109265    0.000000e+00
109266    0.000000e+00
109267    0.000000e+00
109268    0.000000e+00
131114    3.913363e-02
131115    4.099714e-02
131116    4.286065e-02
131117    4.472415e-02
131118    0.000000e+00
131119    0.000000e+00
131120    0.000000e+00
131121    0.000000e+00
Name: position_x, dtype: float64

In [67]:
1.863e-3*7

0.013041

In [71]:
testparticles0.loc[131114:131122, ['position_x', 'position_y']]

        position_x  position_y
row
131114    0.039134    0.000000
131115    0.040997    0.000000
131116    0.042861    0.000000
131117    0.044724    0.000000
131118    0.000000    0.012674
131119    0.000000    0.013277
131120    0.000000    0.013881
131121    0.000000    0.014484

In [76]:
testparticles0x = df0[ (df0['weighting'] == 0.0) & (df0['position_y'] == 0.0)]

In [77]:
testparticles0y = df0[ (df0['weighting'] == 0.0) & (df0['position_x'] == 0.0)]

In [81]:
testparticles0x[['id',  'position_x']]

                         id    position_x
row
21846   9223374235894808576  1.000000e-08
21847   9223374235911585792  1.863506e-03
21848   9223374235928363008  3.727013e-03
21849   9223374235945140224  5.590519e-03
21850   9223374235961917440  7.454025e-03
43702   9223374235978694656  9.317532e-03
43703   9223374235995471872  1.118104e-02
43704   9223374236012249088  1.304454e-02
43705   9223374236029026304  1.490805e-02
65555   9223374236045803520  1.677156e-02
65556   9223374236062580736  1.863506e-02
65557   9223374236079357952  2.049857e-02
65558   9223374236096135168  2.236208e-02
87408   9223374236112912384  2.422558e-02
87409   9223374236129689600  2.608909e-02
87410   9223374236146466816  2.795259e-02
87411   9223374236163244032  2.981610e-02
109261  9223374236180021248  3.167961e-02
109262  9223374236196798464  3.354311e-02
109263  9223374236213575680  3.540662e-02
109264  9223374236230352896  3.727013e-02
131114  9223374236247130112  3.913363e-02
131115  9223374236263907328  4.099714e-02
131116  9223374236280684544  4.286065e-02
131117  9223374236297461760  4.472415e-02

In [83]:
xidarr = testparticles0x['id'].to_numpy()
xidarr[1:] - xidarr[0:-1]

array([16777216, 16777216, 16777216, 16777216, 16777216, 16777216,
       16777216, 16777216, 16777216, 16777216, 16777216, 16777216,
       16777216, 16777216, 16777216, 16777216, 16777216, 16777216,
       16777216, 16777216, 16777216, 16777216, 16777216, 16777216],
      dtype=uint64)

In [85]:
yidarr = testparticles0y['id'].to_numpy()
yidarr[1:] - yidarr[0:-1]

array([16777216, 16777216, 16777216, 16777216, 16777216, 16777216,
       16777216, 16777216, 16777216, 16777216, 16777216, 16777216,
       16777216, 16777216, 16777216, 16777216, 16777216, 16777216,
       16777216, 16777216, 16777216, 16777216, 16777216, 16777216],
      dtype=uint64)

In [86]:
yidarr[0] - xidarr[0]

np.uint64(419430400)

In [87]:
beam4 = series.iterations[iters[4]].particles["beam"]

In [88]:
df4 = beam4.to_df()

In [89]:
testparticles4 = df4[df4['weighting'] == 0.0]

In [90]:
len(testparticles4)

50

In [94]:
testparticles4[['position_x', 'position_y', 'id']]

          position_x    position_y                   id
row
21846   5.642751e-09  0.000000e+00  9223374235894808576
21847   1.051135e-03  0.000000e+00  9223374235911585792
21848   2.100652e-03  0.000000e+00  9223374235928363008
21849   3.148678e-03  0.000000e+00  9223374235945140224
21850   4.195341e-03  0.000000e+00  9223374235961917440
21851   7.592069e-13  7.422689e-10  9223374236314238976
21852   3.369556e-07  4.476841e-05  9223374236331016192
21853   1.348077e-06  8.936799e-05  9223374236347793408
21854   3.034127e-06  1.336299e-04  9223374236364570624
21855   5.396370e-06  1.773854e-04  9223374236381347840
43702   5.240769e-03  0.000000e+00  9223374235978694656
43703   6.285089e-03  0.000000e+00  9223374235995471872
43704   7.328430e-03  0.000000e+00  9223374236012249088
43705   8.370920e-03  0.000000e+00  9223374236029026304
43706   8.436585e-06  2.204656e-04  9223374236398125056
43707   1.215706e-05  2.627016e-04  9223374236414902272
43708   1.656060e-05  3.039245e-04  9223374236431679488
43709   2.165050e-05  3.439656e-04  9223374236448456704
65555   9.412686e-03  0.000000e+00  9223374236045803520
65556   1.045386e-02  0.000000e+00  9223374236062580736
65557   1.149456e-02  0.000000e+00  9223374236079357952
65558   1.253492e-02  0.000000e+00  9223374236096135168
65559   2.743060e-05  3.826558e-04  9223374236465233920
65560   3.390523e-05  4.198262e-04  9223374236482011136
65561   4.107927e-05  4.553079e-04  9223374236498788352
65562   4.895809e-05  4.889319e-04  9223374236515565568
87408   1.357507e-02  0.000000e+00  9223374236112912384
87409   1.461514e-02  0.000000e+00  9223374236129689600
87410   1.565525e-02  0.000000e+00  9223374236146466816
87411   1.669553e-02  0.000000e+00  9223374236163244032
87412   5.754762e-05  5.205291e-04  9223374236532342784
87413   6.685427e-05  5.499306e-04  9223374236549120000
87414   7.688503e-05  5.769672e-04  9223374236565897216
87415   8.764740e-05  6.014699e-04  9223374236582674432
109261  1.773611e-02  0.000000e+00  9223374236180021248
109262  1.877712e-02  0.000000e+00  9223374236196798464
109263  1.981868e-02  0.000000e+00  9223374236213575680
109264  2.086093e-02  0.000000e+00  9223374236230352896
109265  9.914943e-05  6.232696e-04  9223374236599451648
109266  1.113997e-04  6.421971e-04  9223374236616228864
109267  1.244073e-04  6.580832e-04  9223374236633006080
109268  1.381820e-04  6.707589e-04  9223374236649783296
131114  2.190398e-02  0.000000e+00  9223374236247130112
131115  2.294797e-02  0.000000e+00  9223374236263907328
131116  2.399302e-02  0.000000e+00  9223374236280684544
131117  2.503927e-02  0.000000e+00  9223374236297461760
131118  1.527340e-04  6.800549e-04  9223374236666560512
131119  1.680741e-04  6.858020e-04  9223374236683337728
131120  1.842136e-04  6.878312e-04  9223374236700114944
131121  2.011645e-04  6.859732e-04  9223374236716892160

In [ ]:
testparticles4x = df4[ ('weighting' == 0) && ('id' isin xidarr) ]
len(testparticles4x)

In [ ]:
testparticles4x